proxies:
  - name: "WireGuard节点"
    type: wireguard
    server: 207.230.125.177
    port: 51820
    ip: 10.14.0.2/16
    private-key: uE8LS5IM1Voiup89Lwi+QYldG8MCxtrY+SUcaNNgpG4=
    public-key: 1g84fGxVJokKXdMYEJKjN6/opyYN/YSHmrMyw0v6VnM=
    dns: [208.67.222.222, 208.67.220.220]
    udp: true
    mtu: 1280

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "WireGuard节点"

rules:
  - GEOIP,CN,DIRECT  # 国内流量直连
  - MATCH,US-VPN  # 其他流量走美国 VPN
